services:
  db:
    container_name: charkhoneh-db
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    restart: always

  backend:
    container_name: charkhoneh-backend
    build:
      context: .
      dockerfile: ./dockerfiles/dev/django/Dockerfile
    volumes: 
      - ./core:/usr/src/app
    working_dir: /usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
    env_file:
      - ./envs/dev/django/.env
    restart: always
    depends_on:
      - db
      
  locust_master:
    image: locustio/locust
    container_name: locust_master
    command: -f /mnt/locust/locustfile.py --master --host=http://backend:8089
    ports:
      - "8089:8089"
    volumes:
      - ./core/locust:/mnt/locust
    depends_on:
      - backend
    restart: always

  locust_worker:
    image: locustio/locust
    container_name: locust_worker
    command: -f /mnt/locust/locustfile.py --worker --master-host=locust_master
    volumes:
      - ./core/locust:/mnt/locust
    depends_on:
      - locust_master
    restart: always
  
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

volumes:
  postgres-data:
  smtp4dev-data: