# Generated by Django 5.2.16 on 2026-09-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="ContactModel",
        ),
    ]
