# Generated by Django 5.2.16 on 2026-09-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_rename_contact_contactmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmodel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
    ]
