# Generated by Django 5.2.16 on 2026-10-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("partially_sent", "Partially Sent"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
