# Generated by Django 5.2.16 on 2026-09-14 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_emailverificationtoken_user_deactivated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only Persian and English letters and spaces are allowed.",
                        regex="^[a-zA-Zآ-ی\\s]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only Persian and English letters and spaces are allowed.",
                        regex="^[a-zA-Zآ-ی\\s]+$",
                    )
                ],
            ),
        ),
    ]
