# Generated by Django 5.2.16 on 2026-09-14 23:42

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_profile_national_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                validators=[accounts.validators.validate_national_id],
            ),
        ),
    ]
