# Generated by Django 5.2.16 on 2026-08-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="productimagemodel",
            options={"verbose_name": "Image", "verbose_name_plural": "Images"},
        ),
        migrations.AlterModelOptions(
            name="productmodel",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="status",
            field=models.IntegerField(
                choices=[(1, "نمایش"), (2, "عدم نمایش")], default=1
            ),
        ),
    ]
