# Generated by Django 5.2.16 on 2026-09-12 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_subscriber_newsletter_newsletterrecipient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productsـcategory",
                to="shop.productcategory",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
